CREATE DATABASE IF NOT EXISTS rice_mill_erp;
USE rice_mill_erp;
CREATE TABLE roles (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100),description TEXT,is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE permissions (id BIGINT PRIMARY KEY AUTO_INCREMENT,module VARCHAR(100),action VARCHAR(50),slug VARCHAR(120) UNIQUE,description TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE role_permissions (id BIGINT PRIMARY KEY AUTO_INCREMENT,role_id BIGINT,permission_id BIGINT,UNIQUE KEY uq_role_perm(role_id,permission_id),FOREIGN KEY(role_id) REFERENCES roles(id),FOREIGN KEY(permission_id) REFERENCES permissions(id));
CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),email VARCHAR(120) UNIQUE,phone VARCHAR(20),password VARCHAR(255),role_id BIGINT,is_active TINYINT DEFAULT 1,last_login DATETIME NULL,login_attempts INT DEFAULT 0,locked_until DATETIME NULL,created_by BIGINT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE sessions (id VARCHAR(128) PRIMARY KEY,user_id BIGINT,ip_address VARCHAR(45),user_agent TEXT,payload LONGTEXT,last_activity INT,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE audit_logs (id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NULL,action VARCHAR(50),table_name VARCHAR(100),record_id BIGINT,old_values JSON,new_values JSON,ip_address VARCHAR(45),user_agent TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE company (id BIGINT PRIMARY KEY AUTO_INCREMENT,legal_name VARCHAR(200),trade_name VARCHAR(200),gstin VARCHAR(20),pan VARCHAR(20),address TEXT,city VARCHAR(100),state VARCHAR(100),pincode VARCHAR(10),phone VARCHAR(20),email VARCHAR(120),website VARCHAR(160),logo_path VARCHAR(255),financial_year_start DATE,bank_name VARCHAR(120),bank_account_no VARCHAR(80),bank_ifsc VARCHAR(30),invoice_terms TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE uom (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(60),short_name VARCHAR(20),conversion_to_kg DECIMAL(12,4),is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE bag_types (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),weight_capacity_kg DECIMAL(10,2),description TEXT,is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE warehouses (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),location VARCHAR(255),warehouse_type ENUM('paddy','rice','byproduct','general') DEFAULT 'general',capacity_kg DECIMAL(14,2) DEFAULT 0,incharge_name VARCHAR(120),incharge_phone VARCHAR(20),is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- Remaining tables
CREATE TABLE vendors (id BIGINT PRIMARY KEY AUTO_INCREMENT,company_name VARCHAR(200),contact_person VARCHAR(120),gstin VARCHAR(20),pan VARCHAR(20),address TEXT,city VARCHAR(100),state VARCHAR(100),pincode VARCHAR(10),phone VARCHAR(20),email VARCHAR(120),opening_balance DECIMAL(14,2) DEFAULT 0,balance_type ENUM('dr','cr') DEFAULT 'cr',credit_period_days INT DEFAULT 0,bank_name VARCHAR(120),bank_account_no VARCHAR(80),bank_ifsc VARCHAR(30),is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE customers (id BIGINT PRIMARY KEY AUTO_INCREMENT,customer_type ENUM('retail','wholesale','distributor') DEFAULT 'retail',name VARCHAR(200),contact_person VARCHAR(120),gstin VARCHAR(20),phone VARCHAR(20),email VARCHAR(120),billing_address TEXT,shipping_address TEXT,city VARCHAR(100),state VARCHAR(100),pincode VARCHAR(10),opening_balance DECIMAL(14,2) DEFAULT 0,balance_type ENUM('dr','cr') DEFAULT 'dr',credit_limit DECIMAL(14,2) DEFAULT 0,credit_period_days INT DEFAULT 0,price_category VARCHAR(50),is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE paddy_varieties (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),grade VARCHAR(20),avg_yield_percentage DECIMAL(5,2),description TEXT,is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE rice_types (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),process_type ENUM('raw','boiled','steam','parboiled'),grade VARCHAR(20),hsn_code VARCHAR(20),gst_rate DECIMAL(5,2),is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE byproducts (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),uom_id BIGINT,default_selling_price DECIMAL(12,2),hsn_code VARCHAR(20),gst_rate DECIMAL(5,2),is_active TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(uom_id) REFERENCES uom(id));
-- simplified remaining financial/transactional tables
CREATE TABLE purchase_invoices (id BIGINT PRIMARY KEY AUTO_INCREMENT,invoice_no VARCHAR(60) UNIQUE,invoice_date DATE,vendor_id BIGINT,truck_no VARCHAR(30),driver_name VARCHAR(120),driver_phone VARCHAR(20),freight_charges DECIMAL(12,2) DEFAULT 0,labour_charges DECIMAL(12,2) DEFAULT 0,other_charges DECIMAL(12,2) DEFAULT 0,other_charges_narration VARCHAR(255),discount_amount DECIMAL(12,2) DEFAULT 0,total_amount DECIMAL(14,2),warehouse_id BIGINT,status ENUM('draft','final','cancelled') DEFAULT 'draft',financial_year VARCHAR(10),created_by BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE purchase_items (id BIGINT PRIMARY KEY AUTO_INCREMENT,purchase_id BIGINT,paddy_id BIGINT,no_of_sacks DECIMAL(10,2),weight_per_sack_kg DECIMAL(10,2),total_weight_kg DECIMAL(12,2),rate_per_sack DECIMAL(12,2),rate_per_quintal DECIMAL(12,2),gross_amount DECIMAL(14,2),moisture_percentage DECIMAL(5,2),deduction_percentage DECIMAL(5,2),net_weight_kg DECIMAL(12,2),net_amount DECIMAL(14,2));
